# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.3
    hooks:
      - id: commitlint
        name: Check commit message against @commitlint/config-conventional rules
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional@8.3.4']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.3
    hooks:
      - id: rubocop
        exclude: ^Gemfile\.lock$
